### PR TITLE
Add adoption form

### PR DESCRIPTION
**Pull request by mileswwatkins**
I'm not wild about the styling, so shoot me any suggestions! Also, I wrote but didn't use the automatic ZIP code finder, mostly because with the browser asking for location I feel like the UX is a bit rough, but the code's there and working.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
I'll work on the merge conflicts later this weekend!

**Comment by mileswwatkins** [comment]
Merge complete, ready to go! Not sure how my text will perform on mobile, so again definitely shoot me advice or suggested changes on the CSS.

**Comment by heyitsolivia** [comment]
Sweet beans :) I'll check this more thoroughly later later but looking good

**Comment by heyitsolivia** [comment]
:dog: :+1: :dog: :+1: :dog: :+1: :dog: :+1: :dog: :+1: :dog: 

:rocket:

**Pull request merged**
